### ISSUE TITLE
phpBB Debug warnings, messed-up layout, on viewtopic.php

### ISSUE THREAD

**Issue by kingjon3377** [PenoaksDevOps/HolyWorlds-Issues#19] opened 2018-09-12 19:07 UTC
When trying to view any thread, the page first fills up with log-spew type text, which is (too quickly for me to read it) replaced by a version of HW with a few lines of PHP warnings (visible) at the top, then the usual background image, and the HW header at the *bottom* of the screen, and (when I scroll down) the thread below that. A too-large font is used for most everything in the thread---essentially everything except the "Logout", "0 new messages", "View unanswered posts," etc., and the footer---and some posts don't show any text at all. The visible warning/log lines say:

`[phpBB Debug] PHP Warning: in file [ROOT]/includes/bbcode.php on line 488: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead`

(I first ran into this when opening an early-July topic-reply-notification email, but reproduced it on [this thread](https://holyworlds.org/viewtopic.php?f=35&t=9924) linked from the "Announcements and Information" room directly.)

Here's a screenshot showing the log-spew and the dropped header:
![log-spew and dropped header](https://user-images.githubusercontent.com/1522278/45447284-1009d280-b69d-11e8-926b-447594e782e6.png)

And here's a screenshot after I scrolled down enough to show some of the messed-up layout:
![font and layout problems](https://user-images.githubusercontent.com/1522278/45447387-6545e400-b69d-11e8-89a7-be766535b52b.png)

**Comment by BarelyAPrincess** [comment] 2018-09-13 06:03
Was caused by a PHP upgrade from 5.6 to 7.2. Temporarily fixed by muting PHP warnings but truly can only be fixed by upgrading phpBB.

**Closed as completed by BarelyAPrincess** 2018-09-13 06:03 UTC
Labels: bug
